name: "Terraform"

on: 
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read      

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4  

      - name: configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: eu-west-2  

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0"
          terraform_wrapper: false

      - name: Terraform init
        id: init
        run: terraform init
        working-directory: AWS-DEPLOYMENT

      - name: Terraform plan
        id: plan
        run: terraform plan
        working-directory: AWS-DEPLOYMENT
        
      - name: Terraform apply
        id: apply 
        run: terraform apply -auto-approve
        working-directory: AWS-DEPLOYMENT
      
      - name: Terraform destroy
        id: destroy 
        run: terraform destroy -auto-approve
        working-directory: AWS-DEPLOYMENT
    